/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124055-gc67a4554d1-20260420"
#endif /* AVUTIL_FFVERSION_H */
